// apps/desktop/src/renderer/components/ChatView.vue
<template>
  <div class="chat-view">
    <div class="chat-header">
      <span class="chat-title">{{ currentSessionTitle }}</span>
      <n-select v-model:value="store.mode" :options="modeOptions" size="small" style="width: 140px" />
    </div>
    <div class="chat-messages" ref="messagesRef">
      <div v-if="store.nodes.length === 0" class="empty-state">
        <div class="empty-title">开始新的对话</div>
        <div class="empty-subtitle">输入指令，Agent 将自动规划并执行</div>
      </div>
      <template v-else>
        <MessageBubble v-for="node in store.nodes" :key="node.id" :node="node" />
      </template>
    </div>
    <div class="chat-input">
      <n-input v-model:value="inputText" type="textarea" placeholder="输入指令..." :autosize="{ minRows: 1, maxRows: 4 }"
        @keydown.enter.exact.prevent="handleSend" />
      <n-button type="primary" :disabled="!inputText.trim()" @click="handleSend" size="medium">
        <n-icon size="16"><SendOutline /></n-icon>
      </n-button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, nextTick, watch } from 'vue';
import { NInput, NButton, NSelect, NIcon } from 'naive-ui';
import { SendOutline } from '@vicons/ionicons5';
import { useAgentStore } from '../store.js';
import MessageBubble from './MessageBubble.vue';

const store = useAgentStore();
const inputText = ref('');
const messagesRef = ref<HTMLElement>();

const currentSessionTitle = computed(() => {
  const s = store.sessions.find((x) => x.id === store.activeSessionId);
  return s?.title ?? '对话';
});

const modeOptions = [
  { value: 'plan', label: '只读规划' },
  { value: 'ask', label: '逐次确认' },
  { value: 'trusted', label: '信任执行' },
  { value: 'bypass', label: '完全放行' },
];

const handleSend = () => {
  if (!inputText.value.trim()) return;
  store.addMessage(inputText.value.trim());
  inputText.value = '';
};

watch(() => store.nodes.length, async () => {
  await nextTick();
  if (messagesRef.value) {
    messagesRef.value.scrollTop = messagesRef.value.scrollHeight;
  }
});
</script>

<style scoped>
.chat-view {
  flex: 1;
  display: flex;
  flex-direction: column;
  background: #ffffff;
  min-width: 0;
}
.chat-header {
  padding: 12px 24px;
  border-bottom: 1px solid #f0f0f0;
  display: flex;
  align-items: center;
  justify-content: space-between;
  background: #ffffff;
}
.chat-title { font-weight: 500; font-size: 15px; }
.chat-messages {
  flex: 1;
  overflow-y: auto;
  padding: 24px;
  max-width: 800px;
  width: 100%;
  margin: 0 auto;
}
.empty-state {
  text-align: center;
  margin-top: 120px;
  color: #999;
}
.empty-title { font-size: 20px; margin-bottom: 8px; }
.empty-subtitle { font-size: 13px; }
.chat-input {
  padding: 12px 24px 20px;
  border-top: 1px solid #f0f0f0;
  background: #ffffff;
  display: flex;
  gap: 8px;
  align-items: flex-end;
  max-width: 800px;
  width: 100%;
  margin: 0 auto;
}
</style>

// apps/desktop/src/renderer/components/ChatView.tsx
import React, { useRef, useEffect } from 'react';
import { Input, Button, Select, Space } from 'antd';
import { SendOutlined } from '@ant-design/icons';
import { useYiStore } from '../state/store.js';
import type { YiNode, IntentPayload, PonderPayload, PlanPayload, ActionPayload, ResultPayload } from '@yi/shared';

const { TextArea } = Input;

function MessageBubble({ node }: { node: YiNode }) {
  if (node.type === 'intent') {
    const p = node.payload as IntentPayload;
    return (
      <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: 12 }}>
        <div style={{ maxWidth: '70%', padding: '10px 14px', borderRadius: 12, background: '#1677ff', color: '#fff', fontSize: 14 }}>
          {p.input}
        </div>
      </div>
    );
  }

  if (node.type === 'ponder') {
    const p = node.payload as PonderPayload;
    return (
      <div style={{ marginBottom: 12 }}>
        <div style={{ fontSize: 12, color: '#999', marginBottom: 4 }}>分析中...</div>
        <div style={{ padding: '10px 14px', borderRadius: 12, background: '#f5f5f5', fontSize: 13, color: '#666' }}>
          {p.reasoning}
        </div>
      </div>
    );
  }

  if (node.type === 'plan') {
    const p = node.payload as PlanPayload;
    return (
      <div style={{ marginBottom: 12 }}>
        <div style={{ fontSize: 12, color: '#999', marginBottom: 4 }}>执行计划</div>
        <div style={{ padding: '10px 14px', borderRadius: 12, background: '#f5f5f5', fontSize: 13 }}>
          {p.steps.map((step, i) => (
            <div key={step.id} style={{ marginBottom: 4 }}>
              <span style={{ color: '#999' }}>{i + 1}.</span> {step.description}
              <span style={{ marginLeft: 8, fontSize: 11, color: '#bbb' }}>[{step.tool}]</span>
            </div>
          ))}
        </div>
      </div>
    );
  }

  if (node.type === 'action') {
    const p = node.payload as ActionPayload;
    return (
      <div style={{ marginBottom: 8, paddingLeft: 16 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 13 }}>
          <span style={{ color: node.status === 'done' ? '#52c41a' : node.status === 'running' ? '#1677ff' : '#999' }}>●</span>
          <span>{p.tool}</span>
          <span style={{ color: '#999', fontSize: 11 }}>{p.durationMs}ms</span>
          {p.error && <span style={{ color: '#ff4d4f', fontSize: 11 }}>{p.error}</span>}
        </div>
      </div>
    );
  }

  if (node.type === 'result') {
    const p = node.payload as ResultPayload;
    return (
      <div style={{ marginBottom: 12 }}>
        <div style={{ padding: '10px 14px', borderRadius: 12, background: '#f6ffed', border: '1px solid #b7eb8f', fontSize: 13 }}>
          <div style={{ fontWeight: 500, marginBottom: 4 }}>{p.summary}</div>
          <div style={{ fontSize: 12, color: '#666' }}>
            耗时 {(p.durationMs / 1000).toFixed(1)}s · {p.changes.length} 处改动
          </div>
        </div>
      </div>
    );
  }

  return null;
}

export function ChatView() {
  const nodes = useYiStore((s) => s.nodes);
  const mode = useYiStore((s) => s.mode);
  const setMode = useYiStore((s) => s.setMode);
  const addMessage = useYiStore((s) => s.addMessage);
  const bottomRef = useRef<HTMLDivElement>(null);
  const [input, setInput] = React.useState('');

  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [nodes]);

  const handleSend = () => {
    if (!input.trim()) return;
    addMessage(input.trim());
    setInput('');
  };

  return (
    <div style={{ flex: 1, display: 'flex', flexDirection: 'column', background: '#fafafa' }}>
      {/* Header */}
      <div style={{ padding: '12px 20px', borderBottom: '1px solid #f0f0f0', display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: '#fff' }}>
        <span style={{ fontWeight: 500 }}>新对话</span>
        <Space size={8}>
          <Select value={mode} onChange={setMode} size="small" style={{ width: 130 }}
            options={[
              { value: 'plan', label: '只读规划' },
              { value: 'ask', label: '逐次确认' },
              { value: 'trusted', label: '信任执行' },
              { value: 'bypass', label: '完全放行' },
            ]} />
        </Space>
      </div>

      {/* Messages */}
      <div style={{ flex: 1, overflow: 'auto', padding: '20px' }}>
        {nodes.length === 0 && (
          <div style={{ textAlign: 'center', marginTop: 120, color: '#bbb' }}>
            <div style={{ fontSize: 20, marginBottom: 8 }}>弈</div>
            <div style={{ fontSize: 13 }}>开始新的对话</div>
          </div>
        )}
        {nodes.map((n) => <MessageBubble key={n.id} node={n} />)}
        <div ref={bottomRef} />
      </div>

      {/* Input */}
      <div style={{ padding: '12px 20px', borderTop: '1px solid #f0f0f0', background: '#fff' }}>
        <div style={{ display: 'flex', gap: 8 }}>
          <TextArea value={input} onChange={(e) => setInput(e.target.value)}
            placeholder="输入指令..." autoSize={{ minRows: 1, maxRows: 4 }}
            onPressEnter={(e) => { if (!e.shiftKey) { e.preventDefault(); handleSend(); } }}
            style={{ flex: 1 }} />
          <Button type="primary" icon={<SendOutlined />} onClick={handleSend}
            disabled={!input.trim()} style={{ alignSelf: 'flex-end' }} />
        </div>
      </div>
    </div>
  );
}
