// apps/desktop/src/renderer/App.vue
<template>
  <n-config-provider :theme="null">
    <n-message-provider>
      <div class="app-layout">
        <Sidebar />
        <ChatView />
      </div>
    </n-message-provider>
  </n-config-provider>
</template>

<script setup lang="ts">
import { NConfigProvider, NMessageProvider } from 'naive-ui';
import Sidebar from './components/Sidebar.vue';
import ChatView from './components/ChatView.vue';
</script>

<style scoped>
.app-layout { display: flex; height: 100vh; background: #ffffff; }
</style>

// apps/desktop/src/renderer/App.tsx
import React from 'react';
import { ConfigProvider, theme } from 'antd';
import { Sidebar } from './components/Sidebar.js';
import { ChatView } from './components/ChatView.js';
import './styles.css';

export function App() {
  return (
    <ConfigProvider theme={{ algorithm: theme.defaultAlgorithm, token: { colorPrimary: '#1677ff', borderRadius: 6 } }}>
      <div style={{ display: 'flex', height: '100vh' }}>
        <Sidebar />
        <ChatView />
      </div>
    </ConfigProvider>
  );
}
